#+title: My Doom Emacs config
#+DESCRIPTION: This is a config file for my doom emacs
#+AUTHOR: Karl Fredin

* TABLE OF CONTENT
- [[About My Doom][About]]
- [[Beacon][Beacon]]
- [[Centaur Tabs][Centaur Tabs]]
- [[Shell][Shell]]
- [[Line Numbers][Line Numbers]]
- [[Fonts][Fonts]]
- [[Themes][Themes]]
** [[Workspaces][Keybindings]]
*** [[Workspaces][Workspaces]]
- [[Tabs][Tabs]]
- [[Splits][Splits]]
*** [[File Management][File Management]]
- [[Dired][Dired]]
- [[Neotree][Neotree]]
*** [[Terminal][Term]]



*** About My Doom
This is my personal Doom Emacs config that I have written using emacs org mode
so that I can easily make comments inside the document so it's easier to read and
know whats going on. In order to use this config you need to have Doom Emacs installed.


**** Beacon
Never lose your cursor! Beacon makes your cursor shine when you scroll
#+begin_src emacs-lisp :tangle config.el

;; Beacon Mode never lose your cursor
(beacon-mode 1)

#+end_src


**** Centaur Tabs
settings for centaur tabs if you want, change here if
you dont want the tabs to be visible
and change over if you want the tabs to be at the bottom

Keybinding I have set for it for disable the tabs

| Command           | Description | Keybindings |
|-------------------+-------------+-------------|
| centaur-tabs-mode | Toggle Tabs | SPC t h     |


#+begin_src emacs-lisp :tangle config.el

;; Centaur tabs mode on
(setq centaur-tabs-set-bar 'over)
(centaur-tabs-mode t)


#+end_src

**** Shell

Settings for the various shells inside of emacs
#+begin_src emacs-lisp :tangle config.el

;; Shell configuration in emacs
(setq shell-file-name "/bin/zsh"
      vterm-max-scrollback 5000)


#+end_src

**** Line Numbers
Settings for line numbers change relative to example absolute if you want
to see the exact line number of the file. But I always prefer relative
#+begin_src emacs-lisp :tangle config.el

;; Sets line to relative
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode)


#+end_src



**** Fonts
The various font settings for doom emacs. If you want to change the font
Family and size you can do that here. you can set italic font,big font and normal font.
#+begin_src emacs-lisp :tangle config.el

;; Doom fonts
(setq doom-font (font-spec :family "JetBrains Mono" :size 15)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 15)
      doom-big-font (font-spec :family "JetBrains Mono" :size 24))
(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))


#+end_src



**** Themes
Here you can set your prefered theme, I load my themes with the package doom-themes
So I have various themes to choose from. If you want to change theme change the variable
Load-theme to the prefered them you can also do 'SPC h' + t to change theme on the fly
But to make it permanent you need to modify config.el
#+begin_src emacs-lisp :tangle config.el

;; Load package doom-theme
(use-package doom-themes
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  ;; Choose your theme Here
  (load-theme 'doom-nord-aurora t)
  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
  (doom-themes-neotree-config)
  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-nord") ; use "doom-colors" for less minimal icon theme
  (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))

#+end_src



**** Keybindings
This is my custom keybindings I prefer to use. For various task
You can do inside of emacs
***** Workspaces
Keybindings to manipulate workspaces/tabs. To switch work space you can
just do ctrl plus number of workspace you want to move to in order to switch
fast and efficent

****** Tabs
My keybinding for creating new workspaces and switching between them

| Command                | Description                         | Keybindings    |
|------------------------+-------------------------------------+----------------|
| +workspace/new         | Create new workspace                | SPC t n        |
| +workspace/delete      | Remove workspace                    | SPC t d        |
| +workspace/new-named   | New name for workspace              | SPC t N        |
| +workspace/swap-left   | swap workspace to the left          | SPC t j        |
| +workspace/swap-right  | swap workspace to the right         | SPC t k        |
| +workspace/Load        | Load new workspace and switch to it | SPC t L        |
| +workspace/switch-to-0 | Switch to workspace 1               | C-1 or SPC t 1 |
| +workspace/switch-to-1 | Switch to workspace 2               | C-2 or SPC t 2 |
| +workspace/switch-to-2 | Switch to workspace 3               | C-3 or SPC t 3 |
| +workspace/switch-to-3 | Switch to workspace 4               | C-4 or SPC t 4 |
| +workspace/switch-to-4 | Switch to workspace 5               | C-5 or SPC t 5 |
| +workspace/switch-to-5 | Switch to workspace 6               | C-6 or SPC t 6 |
| +workspace/switch-to-6 | Switch to workspace 7               | C-7 or SPC t 7 |
| +workspace/switch-to-7 | Switch to workspace 8               | C-8 or SPC t 8 |
| +workspace/switch-to-8 | Switch to workspace 9               | C-1 or SPC t 9 |
| centaur-tabs-mode      | Toggle Tabs                         | SPC t h        |

#+begin_src emacs-lisp :tangle config.el
;; Tab/workspaces keybindings
(map! :leader
      (:prefix ("t". "buffer")
       :desc "Toggle tabs" "h" #'centaur-tabs-mode
       :desc "Newtab" "n" #'+workspace/new
       :desc "Deletetab" "d" #'+workspace/delete
       :desc "Newname" "N" #'+workspace/new-named
       :desc "Swap Left" "j" #'+workspace/swap-left
       :desc "Swap Right" "k" #'+workspace/swap-right
       :desc "Load tab" "L" #'+workspace/load
       :desc "Switch to tab number 0" "1" #'+workspace/switch-to-0
       :desc "Switch to tab number 1" "2" #'+workspace/switch-to-1
       :desc "Switch to tab number 2" "3" #'+workspace/switch-to-2
       :desc "Switch to tab number 3" "4" #'+workspace/switch-to-3
       :desc "Switch to tab number 4" "5" #'+workspace/switch-to-4
       :desc "Switch to tab number 5" "6" #'+workspace/switch-to-5
       :desc "Switch to tab number 6" "7" #'+workspace/switch-to-6
       :desc "Switch to tab number 7" "8" #'+workspace/switch-to-7
       :desc "Switch to tab number 8" "9" #'+workspace/switch-to-8))

;; Switch workspace using ctrl + number
(map! "C-1" #'+workspace/switch-to-0)
(map! "C-2" #'+workspace/switch-to-1)
(map! "C-3" #'+workspace/switch-to-2)
(map! "C-4" #'+workspace/switch-to-3)
(map! "C-5" #'+workspace/switch-to-4)
(map! "C-6" #'+workspace/switch-to-5)
(map! "C-7" #'+workspace/switch-to-6)
(map! "C-8" #'+workspace/switch-to-7)
(map! "C-9" #'+workspace/switch-to-8)

#+end_src


****** Splits
Custom keybidning to move cursor between splits
I prefer to be able to just move with CTRL + the vim keys

| Command           | Description                    | Keybindings |
|-------------------+--------------------------------+-------------|
| evil-window-right | move cursor to the right split | C-l         |
| evil-window-left  | move cursor to the left split  | C-h         |
| evil-window-up    | move cursor up in the split    | C-k         |
| evil-window-down  | move cursor down in the split  | C-j         |

#+begin_src emacs-lisp :tangle config.el

;; Move around in splits with vim keys
(map! "C-l" #'evil-window-right)
(map! "C-h" #'evil-window-left)
(map! "C-k" #'evil-window-up)
(map! "C-j" #'evil-window-down)

#+end_src

***** File Management
Keybindings for file management inside emacs
using dired and neotree.

****** Dired
Bindings for Dired which is the emacs filemanager
This configuration allows me to use the vim keys inside of dired


| Command                 | Description          | Keybindings |
|-------------------------+----------------------+-------------|
| dired-create-empty-file | Create new file      | SPC d c     |
| dired-create-directory  | Create new directory | SPC d D     |


#+begin_src emacs-lisp :tangle config.el

(map! :leader
      (:prefix ("d". "buffer")
       :desc "Make file in Dired" "c" #'dired-create-empty-file
       :desc "Make directory in Dired" "D" #'dired-create-directory))


(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
  (add-hook 'peep-dired-hook 'evil-normalize-keymaps)


#+end_src


****** Neotree
Keybindings to quickly access the neotree in emacs
neotree is very similar to Nerdtree in vim

| Command         | Description                         | Keybindings |
|-----------------+-------------------------------------+-------------|
| neotree         | Open neotree in current DIR         | SPC d o     |
| neotree-hide    | Hide neotree                        | SPC d h     |
| neotree-dir     | Choose in which DIR to open neotree | SPC d d     |
| neotree-refresh | Refresh Neotree                     | SPC d r     |
| neotree-toggle  | Toggle neotree on and off           | F5          |

#+begin_src emacs-lisp :tangle config.el
;; Neotree Keybindings
(map! :leader
      (:prefix ("d". "buffer")
       :desc "Neotree Open in current Folder" "o" #'neotree
       :desc "Neotree Hide" "h" #'neotree-hide
       :desc "Neotree dir choose directory" "d" #'neotree-dir
       :desc "Neotree refresh" "r" #'neotree-refresh))

(map! "<f5>" #'neotree-toggle)



#+end_src

***** Terminal
Custom keybindings to open termninals within emacs
thins like term,vterm and eshell


| Command | Description             | Keybindings |
|---------+-------------------------+-------------|
| term    | Open Terminal in emacs  | SPC t t     |
| eshell  | Open eshell in emacs    | SPC t e     |
| E       | Toggle eshell           | SPC t E     |
| e       | Open Vterminal in emacs | SPC T V     |

#+begin_src emacs-lisp :tangle config.el
;; Open terminals in Emacs
(map! :leader
      (:prefix ("t". "buffer")
       :desc "Term" "t" #'term
       :desc "Eshell" "e" #'eshell
       :desc "Eshell Popup" "E" #'+eshell/toggle
       :desc "Vterm" "V" #'vterm))

#+end_src
