# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#88c0d0" }

# Hovered
hovered         = { fg = "#191724", bg = "#9ccfd8" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f6c177", italic = true }
find_position = { fg = "#c4a7e7", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#31748f", bg = "#31748f" }
marker_cut      = { fg = "#eb6f92", bg = "#eb6f92" }
marker_marked   = { fg = "#f6c177", bg = "#f6c177" }
marker_selected = { fg = "#9ccfd8", bg = "#9ccfd8" }

# Tab
tab_active   = { fg = "#191724", bg = "#d8dee9" }
tab_inactive = { fg = "#d8dee9", bg = "#6e6a86" }
tab_width    = 1

# Count
count_copied   = { fg = "#303446", bg = "#31748f" }
count_cut      = { fg = "#303446", bg = "#eb6f92" }
count_selected = { fg = "#303446", bg = "#9ccfd8" }

# Border
border_symbol = "│"
border_style  = { fg = "#838ba7" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-frappe.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#6e6a86", bg = "#6e6a86" }

# Mode
mode_normal = { fg = "#303446", bg = "#ebbcba", bold = true }
mode_select = { fg = "#303446", bg = "#9ccfd8", bold = true }
mode_unset  = { fg = "#303446", bg = "#c4a7e7", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#9ccfd8", bg = "#6e6a86" }
progress_error  = { fg = "#eb6f92", bg = "#6e6a86" }

# Permissions
permissions_t = { fg = "#9ccfd8" }
permissions_r = { fg = "#f6c177" }
permissions_w = { fg = "#eb6f92" }
permissions_x = { fg = "#31748f" }
permissions_s = { fg = "#838ba7" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#9ccfd8" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#9ccfd8" }
active   = { fg = "#c4a7e7" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#9ccfd8" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#414559" }
cand            = { fg = "#88c0d0" }
rest            = { fg = "#949cbb" }
desc            = { fg = "#c4a7e7" }
separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#c4a7e7" }
exec    = { fg = "#88c0d0" }
desc    = { fg = "#949cbb" }
hovered = { bg = "#626880", bold = true }
footer  = { fg = "#6e6a86", bg = "#c6d0f5" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
# Images
{ mime = "image/*", fg = "#88c0d0" },

# Videos
{ mime = "video/*", fg = "#e5c890" },
{ mime = "audio/*", fg = "#e5c890" },

# Archives
{ mime = "application/zip",             fg = "#c4a7e7" },
{ mime = "application/gzip",            fg = "#c4a7e7" },
{ mime = "application/x-tar",           fg = "#c4a7e7" },
{ mime = "application/x-bzip",          fg = "#c4a7e7" },
{ mime = "application/x-bzip2",         fg = "#c4a7e7" },
{ mime = "application/x-7z-compressed", fg = "#c4a7e7" },
{ mime = "application/x-rar",           fg = "#c4a7e7" },
{ name = "*.lua", text = "", fg = "#31748f" },
{ name = "*.sh",  fg = "#31748f" },
{ name = "*.org", fg = "#f6c177" },
{ name = "*.py", fg = "#ebbcba" },
{ name = "*.png", fg = "#ebbcba" },
{ name = "*.desktop", text = "", fg = "#f6c177" },

# Fallback
{ name = "*", fg = "#c6d0f5" },
{ name = "*/", fg = "#9ccfd8" },

]


