#!/bin/bash

#declare the paths to where you wants your config files to sync to
dotfiles_repo_path="$HOME/dotfiles-repo"
cloud_path="$HOME/Yandex.Disk/home"


#all the configs you want to sync
declare -A config_sync

config_sync[$HOME/.config/qtile]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/nvim]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/kitty]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/bash]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/fish]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/dunst]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/rofi]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/vifm]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/starship.toml]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/picom]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/conky]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/qutebrowser]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/sxiv]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/urxvt]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/alacritty]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/gtk-3.0]="$dotfiles_repo_path/.config"
config_sync[$HOME/.config/oh-my-zsh/themes]="$dotfiles_repo_path/.config/oh-my-zsh/"
config_sync[$HOME/.zshrc]="$dotfiles_repo_path/"
config_sync[$HOME/.bashrc]="$dotfiles_repo_path/"
config_sync[$HOME/.fehbg]="$dotfiles_repo_path/"
config_sync[$HOME/.NERDTreeBookmarks]="$dotfiles_repo_path/"
config_sync[$HOME/.gtkrc-2.0]="$dotfiles_repo_path/"
config_sync[$HOME/.xmonad]="$dotfiles_repo_path/"
config_sync[$HOME/.spectrwm.conf]="$dotfiles_repo_path/"
config_sync[$HOME/.Xresources]="$dotfiles_repo_path/"
config_sync[$HOME/.tmux.conf.local]="$dotfiles_repo_path/"
config_sync[$HOME/.scripts]="$dotfiles_repo_path/"
config_sync[$HOME/.dmenu]="$dotfiles_repo_path/"
config_sync[$HOME/Documents/lists]="$dotfiles_repo_path/Documents/"
config_sync[$HOME/.local/share/applications]="$dotfiles_repo_path/.local/share/"


declare -A cloud_sync

cloud_sync[$HOME/.config/qtile]="$cloud_path/.config"
cloud_sync[$HOME/.config/nvim]="$cloud_path/.config"
cloud_sync[$HOME/.config/kitty]="$cloud_path/.config"
cloud_sync[$HOME/.config/bash]="$cloud_path/.config"
cloud_sync[$HOME/.config/fish]="$cloud_path/.config"
cloud_sync[$HOME/.config/dunst]="$cloud_path/.config"
cloud_sync[$HOME/.config/picom]="$cloud_path/.config"
cloud_sync[$HOME/.config/vifm]="$cloud_path/.config"
cloud_sync[$HOME/.config/starship.toml]="$cloud_path/.config"
cloud_sync[$HOME/.config/rofi]="$cloud_path/.config"
cloud_sync[$HOME/.config/conky]="$cloud_path/.config"
cloud_sync[$HOME/.config/qutebrowser]="$cloud_path/.config"
cloud_sync[$HOME/.config/sxiv]="$cloud_path/.config"
cloud_sync[$HOME/.config/urxvt]="$cloud_path/.config"
cloud_sync[$HOME/.config/alacritty]="$cloud_path/.config"
cloud_sync[$HOME/.config/gtk-3.0]="$cloud_path/.config"
cloud_sync[$HOME/.config/oh-my-zsh/themes]="$cloud_path/.config/oh-my-zsh/"
cloud_sync[$HOME/.zshrc]="$cloud_path/"
cloud_sync[$HOME/.zsh_history]="$cloud_path/"
cloud_sync[$HOME/.bashrc]="$cloud_path/"
cloud_sync[$HOME/.fehbg]="$cloud_path/"
cloud_sync[$HOME/.NERDTreeBookmarks]="$cloud_path/"
cloud_sync[$HOME/.gtkrc-2.0]="$cloud_path/"
cloud_sync[$HOME/.xmonad]="$cloud_path/"
cloud_sync[$HOME/.spectrwm.conf]="$cloud_path/"
cloud_sync[$HOME/.Xresources]="$cloud_path/"
cloud_sync[$HOME/.tmux.conf.local]="$cloud_path/"
cloud_sync[$HOME/.scripts]="$cloud_path/"
cloud_sync[$HOME/.password-store]="$cloud_path/"
cloud_sync[$HOME/.dmenu]="$cloud_path/"
cloud_sync[$HOME/Documents/lists]="$cloud_path/Documents/"
cloud_sync[$HOME/.local/share/applications]="$cloud_path/.local/share/"



for sync in $(printf '%s\n' "${!config_sync[@]}") ; do

    path=$(printf '%s\n' "${config_sync["${sync}"]}")

    rsync -avh --delete $sync $path 

done

for sync in $(printf '%s\n' "${!cloud_sync[@]}") ; do

    path=$(printf '%s\n' "${cloud_sync["${sync}"]}")

    rsync -avh --delete $sync $path 

done
