[theme]
primary = "#D6ACFF"
secondary = "#BD93F9"
title = "#BD93F9"
playing = "#1e1f28"
playing_selected = "#1e1f28"
playing_bg = "#FF92DF"
highlight = "#1e1f28"
highlight_bg = "#FF79C6"
error = "#1e1f28"
error_bg = "#ff5454"
statusbar = "#1e1f28"
statusbar_progress = "#ff78c5"
statusbar_bg = "#ff78c5"
cmdline = "#8ae9fc"
cmdline_bg = "#1e1f28"
search_match = "#ff6E6E"
