[theme]
primary = "#84A0C6"
secondary = "black"
title = "#91ACD1"
playing = "#161821"
playing_selected = "#161821"
playing_bg = "#B48EAD"
highlight = "#161821"
highlight_bg = "#84A0C6"
error = "#161821"
error_bg = "#E98989"
statusbar = "#161821"
statusbar_progress = "#B48EAD"
statusbar_bg = "#B48EAD"
cmdline = "#84A0C6"
cmdline_bg = "#161821"
search_match = "#E27878"
