[theme]
background = "black"
primary = "#E0AF68"
secondary = "#7AA2F7"
title = "#7AA2F7"
playing = "#1A1B26"
playing_selected = "black"
playing_bg = "#BB9AF7"
highlight = "#1A1B26"
highlight_bg = "#7AA2F7"
error = "#FFFACD"
error_bg = "#F7768E"
statusbar = "#1A1B26"
statusbar_progress = "#7AA2F7"
statusbar_bg = "#7AA2F7"
cmdline = "#E0AF68"
cmdline_bg = "#2E3440"
search_match = "#BB9AF7"
