#!/bin/bash

declare -a options=(
"qutebrowser"
"sudo timeshift-gtk"
"spotify"
"gimp"
"steam"
"kdenlive"
"celluloid"
"kitty  htop"
"neovide"


)


appimage=$(find /opt $HOME/Applications -iname "*.Appimage")


choice=$(printf '%s\n' "${options[@]}" "${appimage[@]}" | wofi --show dmenu  -p "Open App:"  )


 [ -z $choice ] && exitt



$choice





