#!/bin/bash

declare -a options=(

"rainbow_cycle"
"red"
"green"
"blue"
"yellow"
"gold"
"cyan"
"magenta"
"white"
"black"

)

declare -a speed_options=(
"1"
"2"
"3"
)


choice=$(printf '%s\n' "${options[@]}" | wofi --show dmenu -p "Choose color mode: ")

if [ $choice = "rainbow_cycle" ] ; then    

     speed=$(printf '%s\n' "${speed_options[@]}" | wofi --show dmenu -p "Choose speed")
     sudo rogauracore $choice $speed 

else

     sudo rogauracore $choice 
fi




