#!/bin/bash


declare -a options=(

"www.phoenixonline.club"
"data.phoenixonline.club"
"lt.phoenixonline.club"
"plex.phoenixonline.club"


)

#expired=$(sudo certbot certificates  | egrep -i "expiry" | awk -F : '{print $6}' | awk '{print $1}' | uniq | grep  "[0-9]" )


for domain in $(printf '%s\n' "${options[@]}") ; do

   
    sudo certbot  certonly --standalone -d $domain

    sudo cat /etc/letsencrypt/live/$domain/privkey.pem /etc/letsencrypt/live/$domain/fullchain.pem >> /etc/haproxy/certs/$domain.pem


done



