local mywibar = {}

function mywibar.create(s,wibox,seperator,powerline,mylauncher,
                        mytextclock,updateicon,updatewidget,mem,cpu,
                        bat,vol,kernelwidget,theme)

s.mywibox:setup {
        layout = wibox.layout.align.horizontal,
        { -- Left widgets
            seperator.first_main,
            mylauncher,
            powerline.sep_right,
            layout = wibox.layout.fixed.horizontal,
            seperator.first_sec,
            s.mylayoutbox,
            seperator.first_sec,
            seperator.first,
            {
            {s.mytaglist,
             bottom = 2,
             color  = theme.fg_normal,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            s.mypromptbox,
            seperator.first_sec,
            seperator.first_sec,
        },
          -- Middle widget
            s.mytasklist,
        { -- Right widgets
            layout = wibox.layout.fixed.horizontal,
            seperator.first_sec,
            seperator.first_sec,
            powerline.sep_1,
            mytextclock,
            seperator.clock_sep,
            updateicon,
            updatewidget,
            seperator.clock_sep,
            powerline.sep_2,
            seperator.first_sec,
            {
            {seperator.linuxicon,
             bottom = 2,
             color  = theme.fg_icon,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {seperator.small_spr,
             bottom = 2,
             color  = theme.fg_icon,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {kernelwidget,
             bottom = 2,
             color  = theme.fg_icon,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            seperator.first_sec,
            {
            {mem.memicon,
             bottom = 2,
             color  = theme.fg_mem,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {mem.memorywidget,
             bottom = 2,
             color  = theme.fg_mem,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            powerline.sep_4,
            {
            {cpu.cpuicon,
             bottom = 2,
             color  = theme.fg_cpu,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {cpu.cpuwidget,
             bottom = 2,
             color  = theme.fg_cpu,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {cpu.tempicon,
             bottom = 2,
             color  = theme.fg_cpu,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {cpu.tempwidget,
             bottom = 2,
             color  = theme.fg_cpu,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            powerline.sep_3,
            {
            {bat.baticon,
             bottom = 2,
             color  = theme.fg_focus,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {bat.batwidget,
             bottom = 2,
             color  = theme.fg_focus,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            powerline.sep_4,
            {
            {vol.volicon,
             bottom = 2,
             color  = theme.fg_alt,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            {
            {vol.volumewidget,
             bottom = 2,
             color  = theme.fg_alt,
             widget = wibox.container.margin,
            },
             left  = 0,
             right = 0,
             layout = wibox.container.margin,
            },
            powerline.sep_3,
            seperator.first_sec,
            {
            {wibox.widget.systray(),
             bottom = 4,
             top    = 6,
             color  = theme.bg_normal,
             widget = wibox.container.margin,
            },
             left  = 3,
             right = -2,
             layout = wibox.container.margin,
            },
        },
    }

end


return mywibar
