#!/usr/bin/fish 

#This will choose a random bacground for you
#just change the path to fit your needs

set pic (ls /var/pictures/backgrounds/ )
set choose (echo $pic | xargs -n1 | shuf -n1)   

feh  --bg-fill "/var/pictures/backgrounds/$choose"

sudo cp "/var/pictures/backgrounds/$choose" "/usr/share/backgrounds/arch/lockscreen.jpg"  
