version: "2.1"
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
    volumes:
      - /mnt/nextcloud/www:/var/www/html
      - /mnt/nextcloud/data:/var/www/html/data
      - /mnt/nextcloud/config:/var/www/html/config
    ports:
      - 8088:80
    restart: unless-stopped
