#!/bin/bash

#creates all the variables so its easy to modify 
date_log=$( date +%d%m%Y-%H%M )
path_log="$HOME/.scripts/activated/file_backups/logs"
rsync_name_log="rsync-$date_log"
rsync_error_log="error-rsync-$date_log"
tar_name_log="tar-$date_log"
tar_error_log="error-tar-$date_log"

#creates the path_log variable if it doesnt exist
[ -d $path_log ] || mkdir -p $path_log

#creates the backups
/home/karl/.scripts/activated/file_backups/tarball > $path_log/$tar_name_log 2> $path_log/$tar_error_log & /home/karl/.scripts/activated/file_backups/rsync &> $path_log/$rsync_name_log 2> $path_log/$rsync_error_log

#clear all the log files thats older than 1 month
/home/karl/.scripts/activated/file_backups/clear_log

