version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - SERVERURL=www.phoenixonline.club 
      - SERVERPORT=51820 
      - PEERS=1 
      - PEERDNS=172.17.0.10 
      - INTERNAL_SUBNET=192.168.1.0 
      - ALLOWEDIPS=0.0.0.0/0 
    volumes:
      - /media/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
