#!/bin/bash


set LIST  (sudo ls /var/lib/docker/volumes | egrep -vi '(media|dev|downloads|nextcloud_data|metadata.db)')

for l in $LIST 

 
        sudo rsync -avh /var/lib/docker/volumes/$l karl@10.0.0.1:/media/backup/docker_volumes/ --rsync-path="sudo rsync"

end
