#!/bin/bash

dir="/home/karl/nextcloud/Pictures"
top_dir=$(ls $dir)


for top in $top_dir ; do
    
    check_for_files=$(ls -lh $dir/$top | grep -v "^d" | awk '{print $NF}' )  
    check_for_folders=$(ls -lh $dir/$top | grep "^d"  | awk '{print $NF}' )  

    echo $check_for_folders
    


done
