#!/usr/bin/fish 

#This is just a simple script to create backups of my .config folder
#will probably add more paths in the future but for now its only .config it will backup

set backuplocation "/mnt/autofs/backup/homefolder/$USER/archive"
set backupsource  "/home/$USER/.config" "/home/$USER/.tmux.conf" "/home/$USER/.tmux.conf.local"
set date_for_backup (date +%d%m%Y-%H%M )
if [ -d $backuplocation ]

    echo "Nothing to do" &> /dev/null

else 

    mkdir -p $backuplocation 

end 

tar --exclude=BraveSoftware -zcpvf $backuplocation/.config-$date_for_backup.tgz  $backupsource 





