[theme]
background = "black"
primary = "#EBBCBA"
secondary = "#EB6F92"
title = "#EB6F92"
playing = "#191724"
playing_selected = "black"
playing_bg = "#31748f"
highlight = "#191724"
highlight_bg = "#EB6F92"
error = "#FFFACD"
error_bg = "#BF616A"
statusbar = "#191724"
statusbar_progress = "#EB6F92"
statusbar_bg = "#EB6F92"
cmdline = "#EBBCBA"
cmdline_bg = "#2E3440"
search_match = "#9CCFD8"
