format = """
[](#1C4961)\
$os\
$username\
[](bg:#2F79A1 fg:#1C4961)\
$directory\
[](fg:#2F79A1 bg:#3A95C7)\
$git_branch\
$git_status\
[](fg:#3A95C7 bg:#40A9E0)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#40A9E0 bg:#1C4961)\
$docker_context\
[](fg:#1C4961 bg:#33658A)\
$time\
[ ](fg:#33658A)\
$all$character \
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#1C4961 "
style_root = "bg:#1C4961 "
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#1C4961"
disabled = true # Disabled by default

[directory]
style = "bg:#2F79A1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#1C4961"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#3A95C7"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3A95C7"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#40A9E0 "
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
