#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(
"qutebrowser"
"sudo timeshift-gtk"
"spotify"
"gimp"
"steam"
"kdenlive"
"celluloid"
"kitty  htop"
"neovide"


)


appimage=$(find /opt $HOME/Applications -iname "*.Appimage")


choice=$(printf '%s\n' "${options[@]}" "${appimage[@]}" | run  -p "Open App:"  )


 [ -z $choice ] && exit



$choice





