#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# 
#Dm script to change the audio source


source $HOME/.dmenu/.config/dm-script.conf

sinks=$(pactl list sinks | grep -i source | awk '{print $NF}' | sed 's/.monitor//g' ) 

declare -a options=(

$sinks


)

choice=$(printf '%s\n' "${options[@]}" | sed -e 's/alsa_output.//g' | run -p "Choose Source:"  )



[ -z $choice  ] && exit 


fix_choice=$(echo $choice | sed -e 's/^/alsa_output./g')

pactl set-default-sink $fix_choice






