#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(

 "yes" 
 "no" 

)


choice=$(printf '%s\n' ${options[@]} | run  -p "You Sure you wanna logout?" )


kill_this=$( ps aux | grep qtile  | grep python | awk '{print $2}'   )

[ "$choice" = "yes" ] && kill -15 $kill_this 
