#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(

 "yes" 
 "no" 

)


choice=$(printf '%s\n' ${options[@]} | run  -p "You Sure you wanna logout?" )


kill_this=$( ps aux | grep qtile  | grep python | awk '{print $2}'   )

[ "$choice" = "yes" ] && kill -15 $kill_this 
