#!/bin/bash 
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf


list=$(ls -d /usr/share/fonts/*/* | grep -v fonts.dir | grep -v fonts.scale)





choice=$(printf '%s\n' "${list[@]}" | cut -d '/' -f 5,6 | run -p "Font:" )

[ -z $choice ] && exit

create_proper_path="/usr/share/fonts/$choice"

display $create_proper_path 
