#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

emojis=$(cat $HOME/Documents/emojis)


choice=$(printf '%s\n' ${emojis[@]} | run -p "emoji " )


[ -z $choice ] && exit


echo $choice | xclip -selection clipboard


