#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf

emojis=$(cat $HOME/Documents/emojis)


choice=$(printf '%s\n' ${emojis[@]} | run -p "emoji " )


[ -z $choice ] && exit


echo $choice | xclip -selection clipboard


