#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
number=$(seq 1 100)

choice=$(printf '%s\n' "${number[@]}" | run -p "Fan Speed")

[ -z $choice ] && exit

$HOME/.scripts/activated/fan-control.sh set $choice

