#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

source $HOME/.dmenu/.config/dm-script.conf
number=$(seq 1 100)

choice=$(printf '%s\n' "${number[@]}" | run -p "Fan Speed")

[ -z $choice ] && exit

$HOME/.scripts/activated/fan-control.sh set $choice

