#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
declare -A fanmode

fanmode[Turbo]="1"
fanmode[Balance]="0"
fanmode[Silent]="2"



choice=$(printf '%s\n' "${!fanmode[@]}" | run -p "Choose Fan Mode")

[ -z $choice ] && exit

selection=$(printf '%s\n' "${fanmode["${choice}"]}")

cd /sys/devices/platform/asus-nb-wmi   


sudo sh -c "echo $selection >> throttle_thermal_policy"    

