#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
declare -A fanmode

fanmode[Turbo]="1"
fanmode[Balance]="0"
fanmode[Silent]="2"



choice=$(printf '%s\n' "${!fanmode[@]}" | run -p "Choose Fan Mode")

[ -z $choice ] && exit

selection=$(printf '%s\n' "${fanmode["${choice}"]}")

cd /sys/devices/platform/asus-nb-wmi   


sudo sh -c "echo $selection >> throttle_thermal_policy"    

