#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
theme=$( ls $HOME/.config/kitty/kitty-themes/themes )

export kittydir=$HOME/.config/kitty


choice=$(printf '%s\n' "${theme[@]}" | run -p "Choose Theme For Kitty:"   )


 [ -z $choice ]  && exit


unlink $kittydir/theme.conf      

ln -s $HOME/.config/kitty/kitty-themes/themes/$choice $HOME/.config/kitty/theme.conf




