#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
theme=$( ls $HOME/.config/kitty/kitty-themes/themes )

export kittydir=$HOME/.config/kitty


choice=$(printf '%s\n' "${theme[@]}" | run -p "Choose Theme For Kitty:"   )


 [ -z $choice ]  && exit


unlink $kittydir/theme.conf      

ln -s $HOME/.config/kitty/kitty-themes/themes/$choice $HOME/.config/kitty/theme.conf




