#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

#script to kill processes


ps=$( ps ch -eo pid,comm,user | grep $USER )




choice=$(printf '%s\n' "${ps[@]}" | awk '{print $2}' | run  -p "Kill:")

[ -z $choice ] && exit


ps=$( ps ch -eo pid,comm,user | grep $choice | awk '{print $1}' )


#process=$(echo $choice | awk '{ print $1 }' )


kill $ps 2> /dev/null

