#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(

"rainbow_cycle"
"red"
"green"
"blue"
"yellow"
"gold"
"cyan"
"magenta"
"white"
"black"

)

declare -a speed_options=(
"1"
"2"
"3"
)


choice=$(printf '%s\n' "${options[@]}" | run -p "Choose color mode: ")

if [ $choice = "rainbow_cycle" ] ; then    

     speed=$(printf '%s\n' "${speed_options[@]}" | run -p "Choose speed")
     sudo rogauracore $choice $speed 

else

     sudo rogauracore $choice 
fi




