#!/bin/bash

theme=$( ls $HOME/.config/kitty/kitty-themes/themes )

export kittydir=$HOME/.config/kitty


choice=$(printf '%s\n' "${theme[@]}" | rofi -dmenu -p "Choose Theme For Kitty:"   )


 [ -z $choice ]  && exit


unlink $kittydir/theme.conf      

ln -s $HOME/.config/kitty/kitty-themes/themes/$choice $HOME/.config/kitty/theme.conf




