#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf



files=$(ls $HOME/.config/leftwm/themes | grep -v current)
path="$HOME/.config/leftwm/themes"


choice=$(echo "$files" | xargs -n1 | run -p "select theme: " )


unlink $path/current


ln -s $path/$choice $path/current 
