#!/bin/bash




files=$(ls /home/karl/.config/leftwm/themes | grep -v current)
path="$HOME/.config/leftwm/themes"


choice=$(echo "$files" | xargs -n1 | rofi -dmenu -p "select theme: " )


unlink $path/current


ln -s $path/$choice $path/current 
