#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf



files=$(ls $HOME/.config/leftwm/themes | grep -v current)
path="$HOME/.config/leftwm/themes"


choice=$(echo "$files" | xargs -n1 | run -p "select theme: " )


unlink $path/current


ln -s $path/$choice $path/current 
