#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

declare -A countires

countires[Canada]="ca"
countires[Poland]="pl"
countires[Denmark]="dk"
countires[Belgium]="be"
countires[Norway]="no"
countires[Hungary]="hu"
countires[United States]="us"
countires[Austria]="at"
countires[Switzerland]="ch"
countires[Czech Republic]="cz"
countires[United Kingdom]="uk"
countires[France]="fr"
countires[Netherlands]="nl"
countires[Cyprus]="cy"
countires[Germany]="de"
countires[Bosnia and Herzegovina]="ba"
countires[Croatia]="hr"
countires[Taiwan]="tw"
countires[Japan]="jp"
countires[Slovakia]="sk"
countires[Spain]="es"
countires[Italy]="it"
countires[Romania]="ro"
countires[Bulgaria]="bg"
countires[Israel]="il"
countires[Vietnam]="vn"
countires[South Africa]="za"
countires[Luxembourg]="lu"
countires[Malaysia]="my"
countires[Greece]="gr"
countires[Latvia]="lv"
countires[Indonesia]="id"
countires[Portugal]="pt"
countires[Singapore]="sg"
countires[Sweden]="se"
countires[Slovenia]="si"
countires[Brazil]="br"
countires[Australia]="au"
countires[Ireland]="ie"
countires[Argentina]="ar"
countires[Serbia]="rs"
countires[Moldova]="md"
countires[New Zeeland]="nz"
countires[India]="in"
countires[Albania]="al"
countires[Hong Kong]="hk"
countires[Chile]="cl"
countires[Georgia]="ge"
countires[Estonia]="ee"
countires[Iceland]="is"
countires[South Korea]="kr"
countires[North Macedonia]="mk"
countires[Mexico]="mx"
countires[Thailand]="th"
countires[Netherlands]="so"
countires[United Arab Emirates]="ae"
countires[Finland]="fi"
countires[Turkey]="tr"
countires[Ukraine]="ua"
countires[Lithuania]="lt"
countires[Costa Rica]="cr"


selection=$(printf '%s\n' "${!countires[@]}" | run -p "Choose country")

if [ -z "$selection" ] ; then
     
     exit

 else

    abbr=$(printf '%s\n' "${countires["${selection}"]}")
   
    sudo openpyn -c $abbr 
fi
