#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
check=""


while [ -z $check ] ; do

path_group=$(ls -d $HOME/mv/*/* | awk -F / '{print $5}' | sort -u )


choice=$(printf '%s\n' "${path_group[@]}" | sed -e 's/^./\U&/g' | run -p "Choose group:")
choice=$(echo $choice | sed -e 's/^./\L&/g')

[ -z $choice ] && exit

path_ls=$(find /mnt/music/  \( -iname "*.mkv" \) -o \( -iname "*.webm"  \) -o \( -iname "*.mp4" \) | grep $choice  | awk -F / '{print $NF}')


choice_song=$(printf '%s\n' "${path_ls[@]}" "Back" | run -p "Choose song:") 

[ $choice_song != "Back" ] && check="1"

[ -z "$choice_song"  ] && exit || mpv "$HOME/mv/$choice/$choice_song"

done












