#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf

url=$(cat $URL | sed -e "s/^/(/g" -e "s/ /) /g" | grep -v qute)

declare -a options=(

"$url"

)




choice=$(printf '%s\n' "${options[@]}" | run -p "Open Website in fullscreen:")

if [ -z $choice  ] ; then

    exit 

fi 

list=$(echo $choice | awk '{print $NF}'  )


check_https=$(echo $list | grep https )
check_http=$(echo $list | grep http | grep -v https )




if [ -z $check_http ] ; then 

  none="0"

else
  
  convert=$(echo $check_http | sed -e 's/http/https/g')

$FULLSCREEN_BROWSER --new-window --app=$list

exit

fi

if [ -z $check_https ] ; then


$FULLSCREEN_BROWSER --new-window --app=https://$list

  else

$FULLSCREEN_BROWSER --new-window --app=$list


fi

