#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-
#Rofi script that will copy the choosen password to my pass database
list=$(find  $HOME/.password-store/ -iname "*.gpg" | sed -e 's/.gpg//g' -e 's/\/home\/karl\/.password-store//g' -e 's/\///')

declare -a options=($list)

choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -p "<" )

[ -z "$choice" ] && exit 

pass show $choice | xclip -selection clipboard

sleep 20

xsel -cb
