#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-
#Rofi script that will copy the choosen password or username for my pass database
#To make it easy and convinient to sign in to my services 

#Source the config file
source $HOME/.dmenu/.config/dm-script.conf

#This will receive all my passwords from the pass password store
list=$(find  $HOME/.password-store/ -iname "*.gpg" | sed -e 's/.gpg//g' -e 's/\/home\/karl\/.password-store//g' -e 's/\///' | sed -e 's/^karlfredin5@gmail.com//g' -e 's/^karlfredin@hotmail.se//g' -e 's/^phoenix081408@gmail.com//g' -e 's/^karlfredin@gmail.com//g')

#Declares the array for username and password question
declare -a user_or_password=( "username" "password" )

#declare the pass list array
declare -a options=($list)

#the run menu where you make your choice
choice=$(printf '%s\n' "${options[@]}" | run -p "<" )

#Will exit the script if choice is empty
[ -z "$choice" ] && exit 

#Choose if you want to copy username or password
another_choice=$(printf '%s\n' "${user_or_password[@]}" | wofi --show dmenu -p "<")


if [ $another_choice = "username" ] ; then


    user=$(echo $choice | awk -F / '{print $NF}')
   
  if [ "$DISPLAY_SERVER" = "wayland" ] ; then

      wl-copy $user
     
  elif [ "$DISPLAY_SERVER" = "xorg" ] ; then 
      
      echo $user | xclip -selection clipboard
  fi
     
     else

  if [ "$DISPLAY_SERVER" = "wayland" ] ; then
    
    pass=$(pass show $choice)

    wl-copy $pass

    sleep 20

    wl-copy -c
  
 elif [ "$DISPLAY_SERVER" = "xorg"  ] ; then

    xsel -cb

    pass show $choice | xclip -selection clipboard

  fi

  fi




