#!/usr/bin/bash

source $HOME/.dmenu/.config/dm-script.conf

check_back="back"
while [ $check_back = "back" ] ; do
 
players=$(playerctl -l)



choice=$( echo $players "exit" | xargs -n1 | run -p "Choose Instance To Control: " )

[ -z $choice ] && exit
[ $choice = "exit" ] && exit


while true ; do

play_pause=$( printf "play\npause\nnext\nprevious\nback\nexit" | run -p "What action do you want to perform: ?")

check_back="$play_pause"

[ $play_pause = "exit" ] && exit
[ $play_pause = "back" ] && break

playerctl $play_pause -p $choice

done
done
