#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(

"Restart"
"Sleep"
"Shutdown"


)
choice=$(printf '%s\n' "${options[@]}" | run -p "Choose your action")

[ -z $choice ] && exit

[ $choice = "Restart" ] && sudo reboot -ff
[ $choice = "Shutdown" ] && sudo shutdown -ff
[ $choice = "Sleep" ] && sudo systemctl suspend
