#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-
#Script that will restart your computer or make it sleep
source $HOME/.dmenu/.config/dm-script.conf

declare -a options=(

"Restart"
"Sleep"
"Shutdown"


)
choice=$(printf '%s\n' "${options[@]}" | run -p "Choose your action")

[ -z $choice ] && exit

[ $choice = "Restart" ] && sudo reboot -ff
[ $choice = "Shutdown" ] && sudo shutdown -ff
[ $choice = "Sleep" ] && sudo systemctl suspend
