#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(nvidia integrated compute hybrid)

choice=$(printf '%s\n' "${options[@]}" | run -p "Choose your graphics mode (Restart required): ")

[ -z $choice ] && exit

system76-power graphics $choice
