#!/bin/bash


listofbackgrounds=$(ls -d /var/pictures/Wallpapers/* )  
dire=/var/pictures/Wallpapers


#Here you can add custom paths where you have some wallpapers
declare -A morebackgrounds

morebackgrounds[dracula_theme]="/home/karl/Pictures/dracula"
morebackgrounds[kpopwp]="/home/karl/Pictures/kpop/kpopWP"
morebackgrounds[hellovenus]="/home/karl/Pictures/kpop/hellovenus/hellovenus_wp"
morebackgrounds[berrygood]="/home/karl/Pictures/kpop/berrygood/berrygood_wp"
morebackgrounds[bts]="/home/karl/Pictures/kpop/bts/bts_wp"
morebackgrounds[everglow]="/home/karl/Pictures/kpop/everglow/everglow_wp"
morebackgrounds[itzy]="/home/karl/Pictures/kpop/itzy/itzy_wp"
morebackgrounds[laysha]="/home/karl/Pictures/kpop/laysha/laysha_wp"
morebackgrounds[mamamoo]="/home/karl/Pictures/kpop/mamamoo/mamamoo_wp"
morebackgrounds[tri.be]="/home/karl/Pictures/kpop/tri.be/tri.be_wp"
morebackgrounds[blackpink]="/home/karl/Pictures/kpop/blackpink/blackpink_wp"
morebackgrounds[cignature]="/home/karl/Pictures/kpop/cignature/cignature_wp"
morebackgrounds[hot-issue]="/home/karl/Pictures/kpop/hot-issue/hot-issue_wp"
morebackgrounds[ive]="/home/karl/Pictures/kpop/ive/ive_wp"
morebackgroundnds[kpopw]="/home/karl/Pictures/kpop/kpopw/kpopw_wp"
morebackgrounds[lunarsolar]="/home/karl/Pictures/kpop/lunarsolar/lunarsolar_wp"
morebackgrounds[stayc]="/home/karl/Pictures/kpop/stayc/stayc_wp"
morebackgrounds[twice]="/home/karl/Pictures/kpop/twice/twice_wp"
morebackgrounds[dreamcatcher]="/home/karl/Pictures/kpop/dreamcatcher/dreamcatcher_wp"
morebackgrounds[others]="/home/karl/Pictures/kpop/others/others_wp"


choice=$(printf '%s\n' "use_default" "choose_custom_path" "use_dual_wallpaper"  | awk -F / '{print $NF}' | rofi -dmenu -p "Choose your option:"  )


[ -z $choice ] && exit

if [ $choice = "use_dual_wallpaper" ] ; then



listofbackgrounds_left=$(ls -d /var/pictures/Wallpapers_dual/left/* )  
listofbackgrounds_right=$(ls -d /var/pictures/Wallpapers_dual/right/* )  
dire=/var/pictures/wallpapers_dual




choice1=$(printf '%s\n' "${listofbackgrounds_left[@]}" | awk -F / '{print $NF}' | rofi -dmenu -p "Choose your first wallpaper:"  )

[ -z $choice1 ] && exit

choice2=$(printf '%s\n' "${listofbackgrounds_right[@]}" | awk -F / '{print $NF}' | rofi -dmenu -p "Choose your second wallpaper:"  )

[ -z $choice2 ] && exit

make_path1="$dire/left/$choice1"
make_path2="$dire/right/$choice2"



feh --bg-fill "$make_path1" "$make_path2" 


sudo cp $make_path1 /usr/share/backgrounds/arch/lockscreen.jpg
else 

    echo ""

fi



if [ $choice = "choose_custom_path" ] ; then


for more_bg in "${morebackgrounds[@]}" ; do

    empty_or_not=$(ls $more_bg)


[ -z "$empty_or_not" ] || list_containing_wallpaper=$(echo $list_containing_wallpaper $more_bg)

done


custom=$(printf '%s\n'  "${list_containing_wallpaper[@]}" | xargs -n1 | rofi -dmenu -p "Choose your path:"  )


[ -z $custom ] && exit

listofbackgrounds=$(ls -d $custom/* )

choice=""

dire=$(echo $custom)

choice="use_default"

fi


if [ $choice = "use_default" ] ; then

choice=$(printf '%s\n' "${listofbackgrounds[@]}" | awk -F / '{print $NF}' | rofi -dmenu -p "Choose your wallpaper:"  )

[ -z $choice ] && exit

make_path="$dire/$choice"

feh --bg-fill "$make_path" 

sudo cp $make_path /usr/share/backgrounds/arch/lockscreen.jpg
else 

    echo ""

fi
