#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

#Creates the array
declare -a options=(

"$HOME/Pictures/Wallpapers"
"$HOME/Pictures/Arch"
"$HOME/Pictures/Nature/"
"$HOME/Pictures/nord/"


)

#Removes all the directories thats empty from the option
for opt in "${options[@]}" ; do

    check_empty=$(ls $opt/* 2> /dev/null ) 
     
    [ -z "$check_empty" ] || wallpapers=$(echo $wallpapers $opt)

done


#Make your choice
choice=$(printf '%s\n' "${wallpapers[@]}" | xargs -n1 |  run -p "Choose your wallpaper" )

[ -z $choice ] && exit


listofbackgrounds=$(ls -d $choice/* )  

#Change background using sxiv
ls $listofbackgrounds | sxiv -i


