#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
declare -a options=(nvidia integrated compute hybrid)

choice=$(printf '%s\n' "${options[@]}" | run -p "Choose your graphics mode (Restart required): ")

[ -z $choice ] && exit

system76-power graphics $choice
