#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
#                                     
# -*- coding: utf-8 -*-



#dmenu script to delete or create snapshots using timeshift

source $HOME/.dmenu/.config/dm-script.conf

declare -a options=(
"New-snapshot"
"Remove-snapshot")

choice=$(printf '%s\n' "${options[@]}" | run -p "Timeshift Action:")

[ -z $choice ] && exit

[ "$choice" = "New-snapshot" -o "$choice" = "Remove-snapshot" ] || rofi -e "ERROR: Invalid Value"

if [ $choice = "New-snapshot" ] ; then

    rofi -e "Creates new snapshot"
    sudo timeshift --create
fi

if [ $choice = "Remove-snapshot" ] ; then

    snapshots=$(sudo timeshift --list | grep "^[0-9]" | grep -v snapshot)
    
    choice_snapshot=$(printf '%s\n' "${snapshots[@]}" | run -p "Snapshot to remove" )
    
    [ -z $choice_snapshot ] && exit
    
    snapshot_name=$(echo $choice_snapshot | awk '{print $3}')
    
    rofi -e "Removes snapshot $snapshot_name"
    sudo timeshift --delete --snapshot "$snapshot_name"

fi
