#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf
theme=$( ls $HOME/.config/urxvt/themes )

export urxvt_link_path=$HOME

choice=$(printf '%s\n' "${theme[@]}" | run -p "Choose Theme:"   )


if [ -z $choice ] ; then 

echo " "


else

unlink $urxvt_link_path/.Xresources      

ln -s $HOME/.config/urxvt/themes/$choice $HOME/.Xresources 


xrdb $HOME/.Xresources


fi 


