#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf


my_vms=$(virsh -c qemu:///system list --all | awk '{print $2}' | sed -e 's/Name//g' -e '/^$/d' )

echo $my_vms


choice=$(echo "New-VM" $my_vms | xargs -n1 | run -p 'Choose VM: ')

[ -z $choice ] && exit

[ $choice = "New-VM" ] && virt-manager --show-domain-creator --connect qemu:///system && exit 

state=$(virsh list --all | grep $choice | awk '{print $3}') 


if [ "$state" = "shut" ] ; then  
    
    set start_choice (echo "yes" "no" | xargs -n1 | run -p 'VM not running, Do you want to start it ? :')

[ -z $start_choice ] && exit

fi

[ "$start_choice" = "yes" ]  && virsh start $choice 


virt-manager --show-domain-console $choice --connect qemu:///system     



