#!/bin/bash
##____  _                      _      
#|  _ \| |__   ___   ___ _ __ (_)_  __
#| |_) | '_ \ / _ \ / _ \ '_ \| \ \/ /
#|  __/| | | | (_) |  __/ | | | |>  < 
#|_|   |_| |_|\___/ \___|_| |_|_/_/\_\
# -*- coding: utf-8 -*-

source $HOME/.dmenu/.config/dm-script.conf

[ $DISPLAY_SERVER = "wayland" ] && error

choice_bg=$( ls $HOME/Pictures/Wallpapers/ )




declare -a options=(

$choice_bg


)
    

choice=$(printf '%s\n' "${options[@]}" | run -p "Choose background for your lockscreen:"  )
 [ -z $choice ] && exit

ls /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg && sudo unlink /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg


sudo ln -s $HOME/Pictures/backgrounds/$choice /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg
