#!/bin/bash
source $HOME/.dmenu/.config/dm-script.conf
choice_bg=$( ls $HOME/Pictures/Wallpapers/ )


echo $choice_bg


declare -a options=(

$choice_bg


)
    

choice=$(printf '%s\n' "${options[@]}" | run -p "Choose background for your lockscreen:"  )
 [ -z $choice ] && exit

ls /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg && sudo unlink /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg


sudo ln -s $HOME/Pictures/backgrounds/$choice /usr/share/backgrounds/arcolinux/arco-wallpaper.jpg
